services:
  mysql:
    image: mysql:8
    container_name: mysql_laravel
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api_job_portal
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_net

volumes:
  mysql_data:

networks:
  laravel_net:
    driver: bridge
